name: multi_modal
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  dash_chat_2: ^0.0.21
  flutter:
    sdk: flutter
  langchain: ^0.7.7+2
  langchain_openai: ^0.7.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

resolution: workspace
